# Generated by Django 6.0.3 on 2026-06-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(choices=[('', 'Select a job role...'), ('marketing', 'Marketing'), ('fitness_coach', 'Fitness Coach'), ('sales', 'Sales')], default='', max_length=50),
        ),
    ]
