# Generated by Django 6.0.3 on 2026-03-11 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('yoga', 'Yoga'), ('hiit', 'HIIT'), ('strength', 'Strength Training'), ('pilates', 'Mat Pilates'), ('core', 'Core Blast'), ('lbt', 'Legs Bums & Tums')], max_length=50)),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Class duration in minutes')),
                ('trainer_name', models.CharField(max_length=100)),
                ('max_capacity', models.IntegerField(default=15)),
                ('booking_status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='booked', max_length=20)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
