# Generated by Django 6.0.3 on 2026-03-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
